apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ape0oyflx-nodejs
  janus-idp.io/tekton: ape0oyflx-nodejs
  backstage.io/kubernetes-id: ape0oyflx-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ape0oyflx-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
