apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ape0oyflx-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ape0oyflx-nodejs 
  name: ape0oyflx-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ape0oyflx-nodejs 
